#!/bin/bash
set -eu

# The host supplies a read-only rootfs, no network, dropped capabilities,
# no-new-privileges, and no host mounts. /tmp is a noexec tmpfs, so the adapter
# is passed to the guaranteed perl-base interpreter through `perl -`: no
# program is ever written to, or executed from, the workspace.
ulimit -t 15
ulimit -v 524288
ulimit -u 64
ulimit -f 16384
umask 077
export HOME=/tmp
export TEXMFHOME=/tmp/texmf
export TEXMFVAR=/tmp/texmf-var
export openout_any=p
export openin_any=p

workspace=$(mktemp -d /tmp/azeforge-tex.XXXXXX)
renderer_pid=
cleanup() {
  if test -n "$renderer_pid"; then
    kill -TERM -- "-$renderer_pid" 2>/dev/null || true
    wait "$renderer_pid" 2>/dev/null || true
  fi
  rm -rf "$workspace"
}
trap cleanup EXIT
trap 'exit 128' HUP INT TERM

# Read the whole request into a file inside the private workspace, bounded at
# 1 MiB. Anything larger is refused before the renderer runs.
head -c 1048577 >"$workspace/request.json"
if test "$(wc -c <"$workspace/request.json")" -gt 1048576; then
  printf '%s\n' "TeX request exceeds the 1 MiB renderer limit." >&2
  exit 1
fi

cd "$workspace"

# A single session contains the entire batch: every figure's frozen-argv
# pipeline runs inside this managed process group. GNU timeout terminates the
# whole group on expiry; the file-size limit bounds every workspace file. The
# adapter writes the response to standard output and diagnostics to standard
# error, which is captured only for failure classification.
setsid timeout --kill-after=1s 15s perl - "$workspace/request.json" >"$workspace/response.json" 2>"$workspace/log" <<'AZEFORGE_TEX_RENDERER_PERL' &
use strict;
use warnings;

# The batch protocol version this adapter speaks; one result per requested index.
my $PROTOCOL = 'azeforge.tex-renderer/v1';

# Bound on the single serialized response, and the captured-log read cap.
my $RESPONSE_MAX_BYTES = 8388608;
my $LOG_MAX_BYTES = 4194304;

binmode(STDOUT);

sub abort {
  my ($message) = @_;
  print STDERR "$message\n";
  exit 1;
}

sub invalid {
  abort('The TeX renderer received an invalid batch request.');
}

my $request_path = scalar(@ARGV) ? $ARGV[0] : '';
abort('The TeX renderer did not receive a request path.') if $request_path eq '';

# ---------------------------------------------------------------------------
# Hand-rolled JSON reader. The request is generated by JSON.stringify, so key
# order is not significant and unknown keys are ignored; raw UTF-8 is passed
# through unchanged and the standard escapes are decoded.
# ---------------------------------------------------------------------------

open(my $request_handle, '<:raw', $request_path)
  or abort('The TeX renderer could not read its request.');
my $input = do { local $/; <$request_handle> };
close($request_handle);
$input = '' unless defined $input;

my $pos = 0;
my $length = length($input);

sub skip_whitespace {
  while ($pos < $length) {
    my $character = substr($input, $pos, 1);
    last unless $character eq ' ' || $character eq "\t" || $character eq "\n" || $character eq "\r";
    $pos++;
  }
}

sub is_digit {
  my ($character) = @_;
  return $character =~ /^[0-9]$/;
}

sub codepoint_to_utf8 {
  my ($codepoint) = @_;
  return chr($codepoint) if $codepoint < 0x80;
  return chr(0xC0 | ($codepoint >> 6)) . chr(0x80 | ($codepoint & 0x3F)) if $codepoint < 0x800;
  return chr(0xE0 | ($codepoint >> 12)) . chr(0x80 | (($codepoint >> 6) & 0x3F)) . chr(0x80 | ($codepoint & 0x3F)) if $codepoint < 0x10000;
  return chr(0xF0 | ($codepoint >> 18)) . chr(0x80 | (($codepoint >> 12) & 0x3F)) . chr(0x80 | (($codepoint >> 6) & 0x3F)) . chr(0x80 | ($codepoint & 0x3F));
}

sub parse_hex4 {
  invalid() if $pos + 4 > $length;
  my $hex = substr($input, $pos, 4);
  invalid() unless $hex =~ /^[0-9a-fA-F]{4}$/;
  $pos += 4;
  return hex($hex);
}

sub parse_number {
  my $start = $pos;
  $pos++ if $pos < $length && substr($input, $pos, 1) eq '-';
  invalid() if $pos >= $length;
  my $character = substr($input, $pos, 1);
  if ($character eq '0') {
    $pos++;
  } elsif (is_digit($character)) {
    $pos++ while $pos < $length && is_digit(substr($input, $pos, 1));
  } else {
    invalid();
  }
  if ($pos < $length && substr($input, $pos, 1) eq '.') {
    $pos++;
    invalid() if $pos >= $length || !is_digit(substr($input, $pos, 1));
    $pos++ while $pos < $length && is_digit(substr($input, $pos, 1));
  }
  if ($pos < $length && (substr($input, $pos, 1) eq 'e' || substr($input, $pos, 1) eq 'E')) {
    $pos++;
    $pos++ if $pos < $length && (substr($input, $pos, 1) eq '+' || substr($input, $pos, 1) eq '-');
    invalid() if $pos >= $length || !is_digit(substr($input, $pos, 1));
    $pos++ while $pos < $length && is_digit(substr($input, $pos, 1));
  }
  return substr($input, $start, $pos - $start);
}

sub parse_string {
  $pos++;
  my $out = '';
  while (1) {
    invalid() if $pos >= $length;
    my $character = substr($input, $pos, 1);
    $pos++;
    if ($character eq '"') {
      return $out;
    }
    if ($character eq '\\') {
      invalid() if $pos >= $length;
      my $escape = substr($input, $pos, 1);
      $pos++;
      if ($escape eq '"') { $out .= '"'; }
      elsif ($escape eq '\\') { $out .= '\\'; }
      elsif ($escape eq '/') { $out .= '/'; }
      elsif ($escape eq 'n') { $out .= "\n"; }
      elsif ($escape eq 't') { $out .= "\t"; }
      elsif ($escape eq 'r') { $out .= "\r"; }
      elsif ($escape eq 'b') { $out .= "\b"; }
      elsif ($escape eq 'f') { $out .= "\f"; }
      elsif ($escape eq 'u') {
        my $codepoint = parse_hex4();
        if ($codepoint >= 0xD800 && $codepoint <= 0xDBFF) {
          my $low;
          if ($pos + 6 <= $length && substr($input, $pos, 2) eq '\\u' && substr($input, $pos + 2, 4) =~ /^[0-9a-fA-F]{4}$/) {
            my $candidate = hex(substr($input, $pos + 2, 4));
            if ($candidate >= 0xDC00 && $candidate <= 0xDFFF) {
              $low = $candidate;
              $pos += 6;
            }
          }
          $codepoint = defined $low ? (0x10000 + (($codepoint - 0xD800) << 10) + ($low - 0xDC00)) : 0xFFFD;
        } elsif ($codepoint >= 0xDC00 && $codepoint <= 0xDFFF) {
          $codepoint = 0xFFFD;
        }
        $out .= codepoint_to_utf8($codepoint);
      } else {
        invalid();
      }
      next;
    }
    invalid() if ord($character) < 0x20;
    $out .= $character;
  }
}

sub consume_literal {
  my ($literal) = @_;
  invalid() if $pos + length($literal) > $length;
  invalid() if substr($input, $pos, length($literal)) ne $literal;
  $pos += length($literal);
}

sub parse_object {
  $pos++;
  my %object;
  skip_whitespace();
  if ($pos < $length && substr($input, $pos, 1) eq '}') {
    $pos++;
    return \%object;
  }
  while (1) {
    skip_whitespace();
    invalid() if $pos >= $length || substr($input, $pos, 1) ne '"';
    my $key = parse_string();
    skip_whitespace();
    invalid() if $pos >= $length || substr($input, $pos, 1) ne ':';
    $pos++;
    my $value = parse_value();
    $object{$key} = $value;
    skip_whitespace();
    invalid() if $pos >= $length;
    my $separator = substr($input, $pos, 1);
    $pos++;
    return \%object if $separator eq '}';
    next if $separator eq ',';
    invalid();
  }
}

sub parse_array {
  $pos++;
  my @array;
  skip_whitespace();
  if ($pos < $length && substr($input, $pos, 1) eq ']') {
    $pos++;
    return \@array;
  }
  while (1) {
    push @array, parse_value();
    skip_whitespace();
    invalid() if $pos >= $length;
    my $separator = substr($input, $pos, 1);
    $pos++;
    return \@array if $separator eq ']';
    next if $separator eq ',';
    invalid();
  }
}

sub parse_value {
  skip_whitespace();
  invalid() if $pos >= $length;
  my $character = substr($input, $pos, 1);
  return parse_object() if $character eq '{';
  return parse_array() if $character eq '[';
  return parse_string() if $character eq '"';
  if ($character eq 't') { consume_literal('true'); return 1; }
  if ($character eq 'f') { consume_literal('false'); return 0; }
  if ($character eq 'n') { consume_literal('null'); return undef; }
  return parse_number();
}

my $root = parse_value();
skip_whitespace();
invalid() if $pos != $length;
invalid() unless ref($root) eq 'HASH';
invalid() unless defined $root->{protocol} && !ref($root->{protocol}) && $root->{protocol} eq $PROTOCOL;
my $figures = $root->{figures};
invalid() unless ref($figures) eq 'ARRAY';

my %PACKAGE = (
  'circuitikz' => '\\usepackage{circuitikz}',
  'tikz' => '\\usepackage{tikz}',
  'pgfplots' => '\\usepackage{pgfplots}',
  'chemfig' => '\\usepackage{chemfig}',
  'tikz-cd' => '\\usepackage{tikz-cd}',
);
my %TIKZPICTURE = map { $_ => 1 } ('circuitikz', 'tikz', 'pgfplots');

# Byte-identical to documentFor(profile, body) in scripts/tex-renderer-document.mjs.
sub document_for {
  my ($profile, $body) = @_;
  my $package = $PACKAGE{$profile};
  return undef unless defined $package;
  my $wrapped = $TIKZPICTURE{$profile} ? "\\begin{tikzpicture}\n$body\n\\end{tikzpicture}" : $body;
  return "\\documentclass{article}\n"
    . "\\def\\pgfsysdriver{pgfsys-dvisvgm.def}\n"
    . "$package\n"
    . "\\pagestyle{empty}\n"
    . "\\begin{document}\n"
    . "$wrapped\n"
    . "\\end{document}\n";
}

# ---------------------------------------------------------------------------
# Hand-rolled JSON writer: raw UTF-8 passes through, JSON structure is escaped.
# ---------------------------------------------------------------------------

sub json_string {
  my ($value) = @_;
  $value = '' unless defined $value;
  my $out = '"';
  my $position = 0;
  my $count = length($value);
  while ($position < $count) {
    my $character = substr($value, $position, 1);
    my $code = ord($character);
    if ($character eq '"') { $out .= '\\"'; }
    elsif ($character eq '\\') { $out .= '\\\\'; }
    elsif ($character eq "\n") { $out .= '\\n'; }
    elsif ($character eq "\t") { $out .= '\\t'; }
    elsif ($character eq "\r") { $out .= '\\r'; }
    elsif ($character eq "\b") { $out .= '\\b'; }
    elsif ($character eq "\f") { $out .= '\\f'; }
    elsif ($code < 0x20) { $out .= sprintf('\\u%04x', $code); }
    else { $out .= $character; }
    $position++;
  }
  return $out . '"';
}

# ---------------------------------------------------------------------------
# Figure pipeline. Every command is a frozen literal list; the request can
# never contribute an executable, argv entry, or path.
# ---------------------------------------------------------------------------

sub remove_tree {
  my ($path) = @_;
  return unless -e $path || -l $path;
  if (-d $path && !-l $path) {
    if (opendir(my $handle, $path)) {
      my @entries = readdir($handle);
      closedir($handle);
      for my $entry (@entries) {
        next if $entry eq '.' || $entry eq '..';
        remove_tree("$path/$entry");
      }
    }
    rmdir($path);
  } else {
    unlink($path);
  }
}

sub run_in_directory {
  my ($directory, @command) = @_;
  my $child = fork();
  abort('The TeX renderer could not start a compiler process.') unless defined $child;
  if ($child == 0) {
    chdir($directory) or exit 127;
    open(STDOUT, '>', 'run.log') or exit 127;
    open(STDERR, '>&STDOUT') or exit 127;
    exec { $command[0] } @command;
    exit 127;
  }
  waitpid($child, 0);
  return $?;
}

sub succeeded {
  my ($status) = @_;
  my $signal = $status & 127;
  my $exit = $status >> 8;
  return $signal == 0 && $exit == 0;
}

# The failure category for a dead pipeline process. SIGXFSZ is the file-size
# limit; everything else the compilers report is a compile failure.
sub failure_category {
  my ($status) = @_;
  my $signal = $status & 127;
  return 'resource-limit' if $signal == 25;
  return 'compile-failed';
}

sub compile_diagnostic {
  my ($directory, $wrapped, $body) = @_;
  my $diagnostic = {
    code => 'compile-failed',
    message => 'The TeX compiler rejected the figure.',
  };
  open(my $log, '<:raw', "$directory/run.log") or return $diagnostic;
  my $buffer = '';
  read($log, $buffer, $LOG_MAX_BYTES);
  close($log);
  # Best-effort body-relative location from the compiler failure line `l.<line>`.
  if ($buffer =~ /^l\.([0-9]+)\b/m) {
    my $body_start = $wrapped ? 7 : 6;
    my $lines = 1 + ($body =~ tr/\n/\n/);
    my $line = $1 + 0 - $body_start + 1;
    $line = 1 if $line < 1;
    $line = $lines if $line > $lines;
    $diagnostic->{bodyLocation} = { line => $line, column => 1 };
  }
  return $diagnostic;
}

sub error_result {
  my ($index, $code, $message, $location) = @_;
  my $diagnostic = { code => $code, message => $message };
  $diagnostic->{bodyLocation} = $location if defined $location;
  return { index => $index, status => 'error', diagnostic => $diagnostic };
}

sub serialize_result {
  my ($result) = @_;
  my $index = $result->{index};
  if ($result->{status} eq 'ok') {
    return '{"index":' . $index . ',"status":"ok","svg":' . json_string($result->{svg}) . '}';
  }
  my $diagnostic = $result->{diagnostic};
  my $serialized = '{"code":' . json_string($diagnostic->{code}) . ',"message":' . json_string($diagnostic->{message});
  if (defined $diagnostic->{bodyLocation}) {
    $serialized .= ',"bodyLocation":{"line":' . $diagnostic->{bodyLocation}{line}
      . ',"column":' . $diagnostic->{bodyLocation}{column} . '}';
  }
  $serialized .= '}';
  return '{"index":' . $index . ',"status":"error","diagnostic":' . $serialized . '}';
}

# Renders one figure inside its own workspace subdirectory and returns its
# result; a workspace bound is reported per figure, not for the whole batch.
sub render_figure {
  my ($index, $profile, $body) = @_;
  my $wrapped = $TIKZPICTURE{$profile} ? 1 : 0;
  my $document = document_for($profile, $body);
  my $directory = "figure-$index";
  remove_tree($directory);
  return error_result($index, 'resource-limit', 'The figure exceeded the renderer workspace limit.')
    unless mkdir($directory);

  my $write_failed = 0;
  if (open(my $tex, '>:raw', "$directory/figure.tex")) {
    print $tex $document;
    $write_failed = 1 unless close($tex);
  } else {
    $write_failed = 1;
  }
  if ($write_failed) {
    remove_tree($directory);
    return error_result($index, 'resource-limit', 'The figure exceeded the renderer workspace limit.');
  }

  my $result;
  my $latex_status = run_in_directory($directory,
    'latex', '-interaction=nonstopmode', '-halt-on-error', '-no-shell-escape', '-output-format=dvi', 'figure.tex');
  if (!succeeded($latex_status)) {
    if (failure_category($latex_status) eq 'resource-limit') {
      $result = error_result($index, 'resource-limit', 'The figure exceeded the renderer workspace limit.');
    } else {
      my $diagnostic = compile_diagnostic($directory, $wrapped, $body);
      $result = error_result($index, 'compile-failed', 'The TeX compiler rejected the figure.', $diagnostic->{bodyLocation});
    }
  } else {
    my $dvisvgm_status = run_in_directory($directory,
      'dvisvgm', '--page=1', '--no-fonts=1', '--precision=6', '--output=output.svg', 'figure.dvi');
    if (!succeeded($dvisvgm_status)) {
      if (failure_category($dvisvgm_status) eq 'resource-limit') {
        $result = error_result($index, 'resource-limit', 'The figure exceeded the renderer workspace limit.');
      } else {
        $result = error_result($index, 'compile-failed', 'The TeX renderer could not convert the figure to SVG.');
      }
    } else {
      my $svg = '';
      if (open(my $svg_handle, '<:raw', "$directory/output.svg")) {
        $svg = do { local $/; <$svg_handle> };
        close($svg_handle);
      }
      $svg = '' unless defined $svg;
      if ($svg eq '') {
        $result = error_result($index, 'compile-failed', 'The TeX renderer produced no SVG for the figure.');
      } else {
        $result = { index => $index, status => 'ok', svg => $svg };
      }
    }
  }

  remove_tree($directory);
  return $result;
}

# Validate every figure before touching the filesystem; a structurally invalid
# request fails the whole batch rather than fabricating results.
my %seen_index;
for my $figure (@$figures) {
  invalid() unless ref($figure) eq 'HASH';
  my $index = $figure->{index};
  invalid() unless defined $index && !ref($index) && $index =~ /^(?:0|[1-9][0-9]*)$/;
  invalid() if $seen_index{$index}++;
  my $profile = $figure->{profile};
  invalid() unless defined $profile && !ref($profile) && exists $PACKAGE{$profile};
  my $body = $figure->{body};
  invalid() unless defined $body && !ref($body);
}

my @ordered = sort { $a->{index} <=> $b->{index} } @$figures;

my @chunks;
my $identity = defined $ENV{'AZEFORGE_TEX_RENDERER_IDENTITY'} ? $ENV{'AZEFORGE_TEX_RENDERER_IDENTITY'} : '';
my $prefix = '{"protocol":' . json_string($PROTOCOL) . ',"rendererIdentity":' . json_string($identity) . ',"results":[';
my $suffix = ']}';
my $used = length($prefix) + length($suffix);

for my $figure (@ordered) {
  my $index = $figure->{index};
  my $result = render_figure($index, $figure->{profile}, $figure->{body});

  my $chunk = serialize_result($result);
  my $separator = @chunks ? 1 : 0;
  if ($result->{status} eq 'ok' && $used + $separator + length($chunk) > $RESPONSE_MAX_BYTES) {
    $result = error_result($index, 'output-limit', 'The rendered figure exceeded the renderer output limit.');
    $chunk = serialize_result($result);
  }
  $used += $separator + length($chunk);
  push @chunks, $chunk;
}

print $prefix . join(',', @chunks) . $suffix;

exit 0;
AZEFORGE_TEX_RENDERER_PERL
renderer_pid=$!
if ! wait "$renderer_pid"; then
  head -c 4194304 "$workspace/log" >&2
  exit 1
fi

test "$(wc -c <"$workspace/response.json")" -le 8388608
cat "$workspace/response.json"
