selected_scheme scheme-minimal
TEXDIR /texlive
TEXMFCONFIG ~/.texlive2026/texmf-config
TEXMFHOME ~/texmf
TEXMFLOCAL /texlive/texmf-local
TEXMFSYSCONFIG /texlive/texmf-config
TEXMFSYSVAR /texlive/texmf-var
TEXMFVAR ~/.texlive2026/texmf-var
binary_x86_64-linux 1
collection-basic 0
instopt_adjustpath 0
instopt_letter 0
instopt_portable 0
instopt_write18_restricted 0
option_doc 0
option_fmt 0
option_path 0
option_src 0
