import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import test from "node:test";

import { TEX_SVG_NORMALIZER_VERSION, TexSvgError, projectTexSvg } from "../dist/tex-svg.js";

const ROOT = fileURLToPath(new URL("..", import.meta.url));
const ACCESSIBLE = { title: "Accessible & title", description: 'desc "quoted"' };

/** A dvisvgm-shaped document: declaration, generator comment, single quotes. */
const DVISVGM = `<?xml version='1.0' encoding='UTF-8'?>
<!-- This file was generated by dvisvgm 3.6 -->
<svg version='1.1' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' width='28.744946pt' height='28.7449460pt' viewBox='76.712329 52.80199 28.744946 28.744946'>
<title>renderer</title>
<defs>
<clipPath id='clip1'><path d='M0 0L1 1'/></clipPath>
</defs>
<g id='page1' clip-path='url(#clip1)'>
<g transform='translate(76.911579,81.347687)scale(0.9962644,-0.0000001)' fill='#000'>
<path d='M0 0L28.452740 28.45274' fill='none'/>
<use xlink:href='#clip1'/>
<text x='0' y='0'>12.345678901</text>
</g>
</g>
</svg>
`;

const CANONICAL =
  '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" height="28.744946pt" role="img" version="1.1" viewBox="76.712329 52.80199 28.744946 28.744946" width="28.744946pt">' +
  "<title>Accessible &amp; title</title>" +
  "<desc>desc &quot;quoted&quot;</desc>" +
  '<defs><clipPath id="tex-3-clip1"><path d="M0 0L1 1"/></clipPath></defs>' +
  '<g clip-path="url(#tex-3-clip1)" id="tex-3-page1"><g fill="#000" transform="translate(76.911579,81.347687)scale(0.996264,0)">' +
  '<path d="M0 0L28.45274 28.45274" fill="none"/><use xlink:href="#tex-3-clip1"/><text x="0" y="0">12.345678901</text>' +
  "</g></g></svg>";

test("one renderer document becomes one canonical projection", () => {
  const projected = projectTexSvg({ svg: DVISVGM, requestIndex: 3, ...ACCESSIBLE });
  assert.equal(projected, CANONICAL);
});

test("the projection depends on structure, not on source serialization", () => {
  const reordered = DVISVGM.replace(
    "<svg version='1.1' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' width='28.744946pt' height='28.7449460pt' viewBox='76.712329 52.80199 28.744946 28.744946'>",
    "<svg viewBox='76.712329 52.80199 28.744946 28.744946' height='28.7449460pt' width='28.744946pt' xmlns:xlink='http://www.w3.org/1999/xlink' xmlns='http://www.w3.org/2000/svg' version='1.1'>",
  );
  assert.notEqual(reordered, DVISVGM);
  assert.equal(projectTexSvg({ svg: reordered, requestIndex: 3, ...ACCESSIBLE }), CANONICAL);
});

test("identifiers carry the batch index and references follow them", () => {
  const figure = (index) =>
    projectTexSvg({
      svg: `<svg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' viewBox='0 0 10 10'><clipPath id='c'><path d='M0 0L1 1'/></clipPath><g id='page1' clip-path='url(#c)'><use xlink:href='#c'/></g></svg>`,
      requestIndex: index,
      title: "t",
      description: "d",
    });
  const first = figure(0);
  const second = figure(1);
  assert.match(first, /id="tex-0-page1"/);
  assert.match(first, /clip-path="url\(#tex-0-c\)"/);
  assert.match(first, /xlink:href="#tex-0-c"/);
  assert.match(second, /id="tex-1-page1"/);
  assert.match(second, /url\(#tex-1-c\)/);
  assert.doesNotMatch(second, /tex-0-/);
});

test("every construct outside the projection contract is refused", () => {
  const SVG = "http://www.w3.org/2000/svg";
  const cases = [
    ["an empty document", "", "malformed"],
    ["an unterminated document", "<svg", "malformed"],
    ["a non-SVG root", `<div xmlns='${SVG}' viewBox='0 0 1 1'/>`, "malformed"],
    ["a missing SVG namespace", "<svg viewBox='0 0 1 1'/>", "malformed"],
    ["a foreign SVG namespace", "<svg xmlns='http://example.invalid/svg' viewBox='0 0 1 1'/>", "malformed"],
    ["a document type declaration", `<!DOCTYPE svg><svg xmlns='${SVG}' viewBox='0 0 1 1'/>`, "malformed"],
    ["an undeclared prefix", `<svg xmlns='${SVG}' viewBox='0 0 1 1'><x:g/></svg>`, "malformed"],
    ["an embedded script", `<svg xmlns='${SVG}' viewBox='0 0 1 1'><g><script>alert(1)</script></g></svg>`, "unsafe"],
    ["a foreign object", `<svg xmlns='${SVG}' viewBox='0 0 1 1'><foreignObject/></svg>`, "unsafe"],
    ["an event handler", `<svg xmlns='${SVG}' viewBox='0 0 1 1'><g onclick='steal()'/></svg>`, "unsafe"],
    ["an animation", `<svg xmlns='${SVG}' viewBox='0 0 1 1'><animate attributeName='x'/></svg>`, "unsafe"],
    ["an internal stylesheet", `<svg xmlns='${SVG}' viewBox='0 0 1 1'><style>#page1{fill:red}</style></svg>`, "unsafe"],
    ["an imported stylesheet", `<svg xmlns='${SVG}' viewBox='0 0 1 1'><g style='@import url(https://x);'/></svg>`, "external"],
    ["a remote link", `<svg xmlns='${SVG}' viewBox='0 0 1 1'><image href='https://example.invalid/a.png'/></svg>`, "external"],
    ["a remote paint", `<svg xmlns='${SVG}' viewBox='0 0 1 1'><g fill='url(https://example.invalid/p)'/></svg>`, "external"],
    ["an undeclared identifier", `<svg xmlns='${SVG}' xmlns:xlink='http://www.w3.org/1999/xlink' viewBox='0 0 1 1'><use xlink:href='#missing'/></svg>`, "reference"],
    ["an undeclared identifier in a paint", `<svg xmlns='${SVG}' viewBox='0 0 1 1'><g clip-path='url(#missing)'/></svg>`, "reference"],
    ["an empty viewBox", `<svg xmlns='${SVG}' viewBox='0 0 0 1'/>`, "dimensions"],
    ["a non-numeric viewBox", `<svg xmlns='${SVG}' viewBox='0 0 wide 1'/>`, "dimensions"],
    ["an unbounded viewBox", `<svg xmlns='${SVG}' viewBox='0 0 20000 1'/>`, "dimensions"],
    ["geometry without an extent", `<svg xmlns='${SVG}'><g/></svg>`, "dimensions"],
    ["a zero-sized extent", `<svg xmlns='${SVG}' width='0' height='10'/>`, "dimensions"],
  ];
  for (const [name, svg, rejection] of cases) {
    let error;
    try {
      projectTexSvg({ svg, requestIndex: 0, title: "t", description: "d" });
    } catch (thrown) {
      error = thrown;
    }
    assert.ok(error instanceof TexSvgError, name);
    assert.equal(error.rejection, rejection, name);
  }
});

test("a unit-suffixed extent is a valid fallback for a missing viewBox", () => {
  const projected = projectTexSvg({
    svg: "<svg xmlns='http://www.w3.org/2000/svg' width='28.744946pt' height='12pt'><g/></svg>",
    requestIndex: 0,
    title: "t",
    description: "d",
  });
  assert.match(projected, /<(title|desc|g)/);
});

test("the normalizer version is the sealed renderer manifest's version", async () => {
  const manifest = JSON.parse(
    await readFile(
      `${ROOT}release/tex-renderer-v1/tex-renderer-v1.manifest.json`,
      "utf8",
    ),
  );
  assert.equal(manifest.normalizer.version, TEX_SVG_NORMALIZER_VERSION);
});
