import assert from "node:assert/strict";
import { chmod, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import test from "node:test";

import { createCompiler } from "../dist/index.js";

const IDENTITY = `sha256:${"a".repeat(64)}`;
const CIRCUIT_CORPUS = fileURLToPath(
  new URL("../docs/language/06-circuit.aze.md", import.meta.url),
);
const SOURCE = `---
azemark: 2
title: TeX artifacts
---

Text before the figure.

:::: tex
id: filter
title: Analog filter
description: A passive low-pass filter.
profile: tikz
----
\\draw (0,0) -- (1,1);
::::

Text after the figure.
`;

const FIGURE = (width) =>
  `<?xml version='1.0' encoding='UTF-8'?>\n<!-- This file was generated by dvisvgm 3.6 -->\n` +
  `<svg version='1.1' xmlns='http://www.w3.org/2000/svg' width='${width}pt' height='10pt' viewBox='0 0 ${width} 10'>` +
  `<g id='page1'><rect x='0' y='0' width='${width}' height='10' fill='#000'/></g></svg>`;

/** Records every batch the compiler sends, and answers with a chosen figure. */
async function recordingAdapter(directory, name, svg) {
  const record = join(directory, "requests.jsonl");
  const path = join(directory, name);
  await writeFile(
    path,
    `import { appendFileSync } from "node:fs";
const chunks = [];
process.stdin.on("data", (chunk) => chunks.push(chunk));
process.stdin.on("end", () => {
  const request = JSON.parse(Buffer.concat(chunks).toString("utf8"));
  appendFileSync(${JSON.stringify(record)}, JSON.stringify(request) + "\\n");
  const results = request.figures.map((figure) => ({ index: figure.index, status: "ok", svg: ${JSON.stringify(svg)} }));
  process.stdout.write(JSON.stringify({ protocol: request.protocol, rendererIdentity: ${JSON.stringify(IDENTITY)}, results }));
});
`,
    { mode: 0o755 },
  );
  await chmod(path, 0o755);
  return { renderer: { rendererIdentity: IDENTITY, command: process.execPath, args: [path] }, record };
}

test("every Artifact format derives from one TeX projection without rerunning TeX", async (context) => {
  const directory = await mkdtemp(join(tmpdir(), "azeforge-tex-artifacts-"));
  context.after(() => rm(directory, { recursive: true, force: true }));
  const { renderer, record } = await recordingAdapter(directory, "adapter.mjs", FIGURE(20));
  const compiler = createCompiler({ texRenderer: renderer });

  const html = await compiler.compile(SOURCE, { format: "html" });
  const svg = await compiler.compile(SOURCE, { format: "svg" });
  const png = await compiler.compile(SOURCE, { format: "png" });
  const pdf = await compiler.compile(SOURCE, { format: "pdf" });
  for (const [format, compiled] of Object.entries({ html, svg, png, pdf })) {
    assert.deepEqual(compiled.diagnostics, [], format);
    assert.ok(compiled.artifact !== undefined, format);
  }

  // One renderer batch per compilation, whatever Artifact format is asked for.
  const requests = (await readFile(record, "utf8")).trim().split("\n").map((line) => JSON.parse(line));
  assert.equal(requests.length, 4);
  assert.deepEqual(requests.map(({ figures }) => figures.length), [1, 1, 1, 1]);
  assert.deepEqual(requests.map(({ figures }) => figures[0].profile), Array(4).fill("tikz"));

  // The HTML and SVG Artifacts carry the identical canonical projection.
  const projection = /<figure class="aze-tex"[\s\S]*?<\/figure>/.exec(
    Buffer.from(html.artifact.bytes).toString("utf8"),
  )?.[0];
  assert.ok(projection, "the HTML Artifact carries the TeX figure");
  assert.ok(
    Buffer.from(svg.artifact.bytes).toString("utf8").includes(projection),
    "the SVG Artifact carries the same projection",
  );
  assert.match(projection, /<title>Analog filter<\/title>/);
  assert.doesNotMatch(projection, /dvisvgm|<\?xml/);

  // The raster and print Artifacts are derived from that projection: a
  // different renderer figure changes their bytes.
  const other = await recordingAdapter(directory, "other.mjs", FIGURE(40));
  const otherCompiler = createCompiler({ texRenderer: other.renderer });
  const otherPng = await otherCompiler.compile(SOURCE, { format: "png" });
  const otherPdf = await otherCompiler.compile(SOURCE, { format: "pdf" });
  assert.notEqual(png.artifact.metadata.artifactHash, otherPng.artifact?.metadata.artifactHash);
  assert.notEqual(pdf.artifact.metadata.artifactHash, otherPdf.artifact?.metadata.artifactHash);

  // Every format is deterministic for one projection.
  const repeated = await compiler.compile(SOURCE, { format: "png" });
  assert.equal(png.artifact.metadata.artifactHash, repeated.artifact?.metadata.artifactHash);
  const repeatedPdf = await compiler.compile(SOURCE, { format: "pdf" });
  assert.equal(pdf.artifact.metadata.artifactHash, repeatedPdf.artifact?.metadata.artifactHash);
});

test("a Circuit-only corpus Source matches every Artifact with and without a TeX adapter", async (context) => {
  const directory = await mkdtemp(join(tmpdir(), "azeforge-tex-circuit-artifacts-"));
  context.after(() => rm(directory, { recursive: true, force: true }));
  const invoked = join(directory, "invoked");
  const adapterPath = join(directory, "must-not-run.mjs");
  await writeFile(
    adapterPath,
    `import { writeFileSync } from "node:fs";
writeFileSync(${JSON.stringify(invoked)}, "");
process.stdin.resume();
`,
    { mode: 0o755 },
  );
  await chmod(adapterPath, 0o755);
  const withRenderer = createCompiler({
    texRenderer: {
      rendererIdentity: IDENTITY,
      command: process.execPath,
      args: [adapterPath],
    },
  });
  const withoutRenderer = createCompiler();
  const corpus = await readFile(CIRCUIT_CORPUS, "utf8");

  for (const format of ["html", "svg", "png", "pdf"]) {
    const adapterResult = await withRenderer.compile(corpus, { format });
    const nativeResult = await withoutRenderer.compile(corpus, { format });
    assert.ok(adapterResult.artifact !== undefined, format);
    assert.deepEqual(adapterResult.document, nativeResult.document, format);
    assert.deepEqual(adapterResult.diagnostics, nativeResult.diagnostics, format);
    assert.equal(adapterResult.contentHash, nativeResult.contentHash, format);
    assert.equal(
      adapterResult.artifact.metadata.artifactHash,
      nativeResult.artifact?.metadata.artifactHash,
      format,
    );
    assert.equal(
      adapterResult.artifact.metadata.rendererFingerprint,
      nativeResult.artifact?.metadata.rendererFingerprint,
      format,
    );
    assert.deepEqual(adapterResult.artifact.bytes, nativeResult.artifact?.bytes, format);
  }
  await assert.rejects(readFile(invoked), { code: "ENOENT" });
});
