import type { Theme } from "./model.js";

export const defaultTheme: Theme = Object.freeze({
  id: "default",
  version: "1.0.0",
  title: "Default",
  colorScheme: "light",
  colors: Object.freeze({
    background: "#ffffff",
    foreground: "#171717",
    muted: "#5f6368",
  }),
  typography: Object.freeze({
    proseFontFamily: "Inter",
    bodyFontWeight: 400,
    headingFontWeight: 700,
    lineHeight: 1.6,
    headingLineHeight: 1.2,
    paragraphSpacingEm: 1,
  }),
  geometry: Object.freeze({
    canvasWidthPx: 960,
    contentWidthPx: 800,
    paddingPx: 48,
  }),
  diagram: Object.freeze({
    nodeFill: "#ffffff",
    nodeStroke: "#3f4652",
    nodeStrokeWidthPx: 1.2,
    nodeLabelFontSizePx: 14,
    nodeLabelLineHeightPx: 20,
    groupFill: "#f1f3f6",
    groupStroke: "#8a93a3",
    groupStrokeWidthPx: 1.4,
    groupLabelFontSizePx: 16,
    groupLabelLineHeightPx: 22,
    groupDepthOpacityStep: 0.12,
    edgeStroke: "#3f4652",
    edgeStrokeWidthPx: 1.4,
    edgeLabelFontSizePx: 12,
    edgeLabelLineHeightPx: 17,
    edgeLabelBackground: "#ffffff",
    arrowFill: "#3f4652",
    portFill: "#ffffff",
    portStroke: "#3f4652",
    portStrokeWidthPx: 1,
    portSizePx: 8,
    labelFontFamily: "Inter",
    minimumLabelFontSizePx: 10,
  }),
  models: Object.freeze({
    boxFill: "#ffffff",
    boxStroke: "#3f4652",
    boxStrokeWidthPx: 1.2,
    boxCornerRadiusPx: 6,
    headerFill: "#eef1f5",
    dividerStroke: "#8a93a3",
    dividerStrokeWidthPx: 1,
    labelFontFamily: "Inter",
    labelFontSizePx: 14,
    labelLineHeightPx: 20,
    memberFontSizePx: 12,
    memberLineHeightPx: 17,
    captionFontSizePx: 11,
    markerFontSizePx: 10,
    markerInk: "#3f4652",
    paddingXPx: 12,
    paddingYPx: 8,
    columnGapPx: 32,
    wrapWidthPx: 220,
    lifelineStroke: "#8a93a3",
    lifelineStrokeWidthPx: 1,
    lifelineDash: "6 4",
    activationFill: "#ffffff",
    activationStroke: "#3f4652",
    activationWidthPx: 10,
    messageStroke: "#3f4652",
    messageStrokeWidthPx: 1.4,
    arrowFill: "#3f4652",
    selfMessageWidthPx: 36,
    noteFill: "#fdf6e3",
    noteStroke: "#8a6d3b",
    fragmentStroke: "#3f4652",
    fragmentStrokeWidthPx: 1.2,
    fragmentDash: "7 4",
    fragmentLabelFill: "#eef1f5",
    rankGapPx: 48,
    rowGapPx: 36,
    diamondSizePx: 10,
    minimumFontSizePx: 10,
  }),
  control: Object.freeze({
    blockFill: "#ffffff",
    blockStroke: "#3f4652",
    blockStrokeWidthPx: 1.2,
    blockLabelFontSizePx: 14,
    blockLabelLineHeightPx: 20,
    signalLabelFontSizePx: 12,
    signalLabelLineHeightPx: 17,
    edgeStroke: "#3f4652",
    edgeStrokeWidthPx: 1.4,
    edgeLabelBackground: "#ffffff",
    arrowFill: "#3f4652",
    sumFill: "#ffffff",
    sumStroke: "#3f4652",
    sumStrokeWidthPx: 1.2,
    sumSignFontSizePx: 13,
    takeoffFill: "#3f4652",
    takeoffRadiusPx: 3,
    stubFill: "#ffffff",
    stubStroke: "#3f4652",
    stubStrokeWidthPx: 1.2,
    stubLabelFontSizePx: 12,
    stubLabelLineHeightPx: 17,
    labelFontFamily: "Inter",
    minimumLabelFontSizePx: 10,
  }),
  freeBody: Object.freeze({
    bodyFill: "#ffffff",
    bodyStroke: "#3f4652",
    bodyStrokeWidthPx: 1.2,
    pointRadiusPx: 2.5,
    pointFill: "#3f4652",
    pointStroke: "#3f4652",
    forceStroke: "#3f4652",
    forceStrokeWidthPx: 1.6,
    forceArrowFill: "#3f4652",
    arrowheadMinLengthPx: 8,
    momentStroke: "#3f4652",
    momentStrokeWidthPx: 1.4,
    momentFill: "#3f4652",
    axisStroke: "#8a93a3",
    axisStrokeWidthPx: 1,
    axisDash: "5 4",
    dimensionStroke: "#8a93a3",
    dimensionStrokeWidthPx: 1,
    tickSizePx: 5,
    labelFontFamily: "Inter",
    labelFontSizePx: 12,
    markFontSizePx: 11,
    minimumLabelFontSizePx: 10,
  }),
});

export const academicTheme: Theme = Object.freeze({
  id: "academic",
  version: "1.0.0",
  title: "Academic",
  colorScheme: "light",
  colors: Object.freeze({
    background: "#fdfcf9",
    foreground: "#1c1917",
    muted: "#78716c",
  }),
  typography: Object.freeze({
    proseFontFamily: "Inter",
    bodyFontWeight: 400,
    headingFontWeight: 700,
    lineHeight: 1.7,
    headingLineHeight: 1.3,
    paragraphSpacingEm: 1.1,
  }),
  geometry: Object.freeze({
    canvasWidthPx: 880,
    contentWidthPx: 700,
    paddingPx: 56,
  }),
  diagram: Object.freeze({
    nodeFill: "#ffffff",
    nodeStroke: "#44403c",
    nodeStrokeWidthPx: 1.2,
    nodeLabelFontSizePx: 15,
    nodeLabelLineHeightPx: 21,
    groupFill: "#f3f1ea",
    groupStroke: "#8a8377",
    groupStrokeWidthPx: 1.4,
    groupLabelFontSizePx: 17,
    groupLabelLineHeightPx: 24,
    groupDepthOpacityStep: 0.12,
    edgeStroke: "#44403c",
    edgeStrokeWidthPx: 1.4,
    edgeLabelFontSizePx: 12,
    edgeLabelLineHeightPx: 17,
    edgeLabelBackground: "#fdfcf9",
    arrowFill: "#44403c",
    portFill: "#fdfcf9",
    portStroke: "#44403c",
    portStrokeWidthPx: 1,
    portSizePx: 8,
    labelFontFamily: "Inter",
    minimumLabelFontSizePx: 10,
  }),
  models: Object.freeze({
    boxFill: "#ffffff",
    boxStroke: "#44403c",
    boxStrokeWidthPx: 1.2,
    boxCornerRadiusPx: 4,
    headerFill: "#f3f1ea",
    dividerStroke: "#8a8377",
    dividerStrokeWidthPx: 1,
    labelFontFamily: "Inter",
    labelFontSizePx: 15,
    labelLineHeightPx: 21,
    memberFontSizePx: 12,
    memberLineHeightPx: 18,
    captionFontSizePx: 11,
    markerFontSizePx: 10,
    markerInk: "#44403c",
    paddingXPx: 13,
    paddingYPx: 9,
    columnGapPx: 34,
    wrapWidthPx: 230,
    lifelineStroke: "#8a8377",
    lifelineStrokeWidthPx: 1,
    lifelineDash: "6 4",
    activationFill: "#ffffff",
    activationStroke: "#44403c",
    activationWidthPx: 10,
    messageStroke: "#44403c",
    messageStrokeWidthPx: 1.4,
    arrowFill: "#44403c",
    selfMessageWidthPx: 38,
    noteFill: "#fbf6e8",
    noteStroke: "#8a6d3b",
    fragmentStroke: "#44403c",
    fragmentStrokeWidthPx: 1.2,
    fragmentDash: "7 4",
    fragmentLabelFill: "#f3f1ea",
    rankGapPx: 50,
    rowGapPx: 38,
    diamondSizePx: 10,
    minimumFontSizePx: 10,
  }),
  control: Object.freeze({
    blockFill: "#ffffff",
    blockStroke: "#44403c",
    blockStrokeWidthPx: 1.2,
    blockLabelFontSizePx: 15,
    blockLabelLineHeightPx: 21,
    signalLabelFontSizePx: 12,
    signalLabelLineHeightPx: 17,
    edgeStroke: "#44403c",
    edgeStrokeWidthPx: 1.4,
    edgeLabelBackground: "#fdfcf9",
    arrowFill: "#44403c",
    sumFill: "#ffffff",
    sumStroke: "#44403c",
    sumStrokeWidthPx: 1.2,
    sumSignFontSizePx: 14,
    takeoffFill: "#44403c",
    takeoffRadiusPx: 3,
    stubFill: "#fdfcf9",
    stubStroke: "#44403c",
    stubStrokeWidthPx: 1.2,
    stubLabelFontSizePx: 12,
    stubLabelLineHeightPx: 17,
    labelFontFamily: "Inter",
    minimumLabelFontSizePx: 10,
  }),
  freeBody: Object.freeze({
    bodyFill: "#ffffff",
    bodyStroke: "#44403c",
    bodyStrokeWidthPx: 1.2,
    pointRadiusPx: 2.5,
    pointFill: "#44403c",
    pointStroke: "#44403c",
    forceStroke: "#44403c",
    forceStrokeWidthPx: 1.6,
    forceArrowFill: "#44403c",
    arrowheadMinLengthPx: 8,
    momentStroke: "#44403c",
    momentStrokeWidthPx: 1.4,
    momentFill: "#44403c",
    axisStroke: "#8a8377",
    axisStrokeWidthPx: 1,
    axisDash: "5 4",
    dimensionStroke: "#8a8377",
    dimensionStrokeWidthPx: 1,
    tickSizePx: 5,
    labelFontFamily: "Inter",
    labelFontSizePx: 12,
    markFontSizePx: 11,
    minimumLabelFontSizePx: 10,
  }),
});

export const darkPresentationTheme: Theme = Object.freeze({
  id: "dark-presentation",
  version: "1.0.0",
  title: "Dark Presentation",
  colorScheme: "dark",
  colors: Object.freeze({
    background: "#0f172a",
    foreground: "#e2e8f0",
    muted: "#94a3b8",
  }),
  typography: Object.freeze({
    proseFontFamily: "Inter",
    bodyFontWeight: 400,
    headingFontWeight: 700,
    lineHeight: 1.5,
    headingLineHeight: 1.2,
    paragraphSpacingEm: 1,
  }),
  geometry: Object.freeze({
    canvasWidthPx: 1280,
    contentWidthPx: 1024,
    paddingPx: 64,
  }),
  diagram: Object.freeze({
    nodeFill: "#1e293b",
    nodeStroke: "#cbd5e1",
    nodeStrokeWidthPx: 1.2,
    nodeLabelFontSizePx: 16,
    nodeLabelLineHeightPx: 22,
    groupFill: "#16213a",
    groupStroke: "#94a3b8",
    groupStrokeWidthPx: 1.4,
    groupLabelFontSizePx: 18,
    groupLabelLineHeightPx: 25,
    groupDepthOpacityStep: 0.12,
    edgeStroke: "#cbd5e1",
    edgeStrokeWidthPx: 1.4,
    edgeLabelFontSizePx: 14,
    edgeLabelLineHeightPx: 20,
    edgeLabelBackground: "#0f172a",
    arrowFill: "#cbd5e1",
    portFill: "#0f172a",
    portStroke: "#cbd5e1",
    portStrokeWidthPx: 1,
    portSizePx: 8,
    labelFontFamily: "Inter",
    minimumLabelFontSizePx: 10,
  }),
  models: Object.freeze({
    boxFill: "#1e293b",
    boxStroke: "#cbd5e1",
    boxStrokeWidthPx: 1.2,
    boxCornerRadiusPx: 6,
    headerFill: "#16213a",
    dividerStroke: "#94a3b8",
    dividerStrokeWidthPx: 1,
    labelFontFamily: "Inter",
    labelFontSizePx: 16,
    labelLineHeightPx: 22,
    memberFontSizePx: 13,
    memberLineHeightPx: 19,
    captionFontSizePx: 12,
    markerFontSizePx: 11,
    markerInk: "#cbd5e1",
    paddingXPx: 14,
    paddingYPx: 10,
    columnGapPx: 40,
    wrapWidthPx: 260,
    lifelineStroke: "#94a3b8",
    lifelineStrokeWidthPx: 1,
    lifelineDash: "6 4",
    activationFill: "#1e293b",
    activationStroke: "#cbd5e1",
    activationWidthPx: 12,
    messageStroke: "#cbd5e1",
    messageStrokeWidthPx: 1.4,
    arrowFill: "#cbd5e1",
    selfMessageWidthPx: 40,
    noteFill: "#26334d",
    noteStroke: "#cbd5e1",
    fragmentStroke: "#cbd5e1",
    fragmentStrokeWidthPx: 1.2,
    fragmentDash: "7 4",
    fragmentLabelFill: "#16213a",
    rankGapPx: 56,
    rowGapPx: 44,
    diamondSizePx: 12,
    minimumFontSizePx: 10,
  }),
  control: Object.freeze({
    blockFill: "#1e293b",
    blockStroke: "#cbd5e1",
    blockStrokeWidthPx: 1.2,
    blockLabelFontSizePx: 16,
    blockLabelLineHeightPx: 22,
    signalLabelFontSizePx: 14,
    signalLabelLineHeightPx: 20,
    edgeStroke: "#cbd5e1",
    edgeStrokeWidthPx: 1.4,
    edgeLabelBackground: "#0f172a",
    arrowFill: "#cbd5e1",
    sumFill: "#1e293b",
    sumStroke: "#cbd5e1",
    sumStrokeWidthPx: 1.2,
    sumSignFontSizePx: 15,
    takeoffFill: "#cbd5e1",
    takeoffRadiusPx: 3.5,
    stubFill: "#1e293b",
    stubStroke: "#cbd5e1",
    stubStrokeWidthPx: 1.2,
    stubLabelFontSizePx: 14,
    stubLabelLineHeightPx: 20,
    labelFontFamily: "Inter",
    minimumLabelFontSizePx: 10,
  }),
  freeBody: Object.freeze({
    bodyFill: "#1e293b",
    bodyStroke: "#cbd5e1",
    bodyStrokeWidthPx: 1.2,
    pointRadiusPx: 3,
    pointFill: "#cbd5e1",
    pointStroke: "#cbd5e1",
    forceStroke: "#cbd5e1",
    forceStrokeWidthPx: 1.6,
    forceArrowFill: "#cbd5e1",
    arrowheadMinLengthPx: 9,
    momentStroke: "#cbd5e1",
    momentStrokeWidthPx: 1.4,
    momentFill: "#cbd5e1",
    axisStroke: "#94a3b8",
    axisStrokeWidthPx: 1,
    axisDash: "5 4",
    dimensionStroke: "#94a3b8",
    dimensionStrokeWidthPx: 1,
    tickSizePx: 5,
    labelFontFamily: "Inter",
    labelFontSizePx: 14,
    markFontSizePx: 13,
    minimumLabelFontSizePx: 10,
  }),
});

export const builtInThemes: readonly Theme[] = Object.freeze([
  defaultTheme,
  academicTheme,
  darkPresentationTheme,
]);

export function copyAndFreezeTheme(theme: Theme): Theme {
  return Object.freeze({
    id: theme.id,
    version: theme.version,
    title: theme.title,
    colorScheme: theme.colorScheme,
    colors: Object.freeze({ ...theme.colors }),
    typography: Object.freeze({ ...theme.typography }),
    geometry: Object.freeze({ ...theme.geometry }),
    diagram: Object.freeze({ ...theme.diagram }),
    models: Object.freeze({ ...theme.models }),
    control: Object.freeze({ ...theme.control }),
    freeBody: Object.freeze({ ...theme.freeBody }),
  });
}
