import type { Theme } from "./model.js";

export const defaultTheme: Theme = Object.freeze({
  id: "default",
  version: "1.0.0",
  title: "Default",
  colorScheme: "light",
  colors: Object.freeze({
    background: "#ffffff",
    foreground: "#171717",
    muted: "#5f6368",
  }),
  typography: Object.freeze({
    proseFontFamily: "Inter",
    bodyFontWeight: 400,
    headingFontWeight: 700,
    lineHeight: 1.6,
    headingLineHeight: 1.2,
    paragraphSpacingEm: 1,
  }),
  geometry: Object.freeze({
    canvasWidthPx: 960,
    contentWidthPx: 800,
    paddingPx: 48,
  }),
  diagram: Object.freeze({
    nodeFill: "#ffffff",
    nodeStroke: "#3f4652",
    nodeStrokeWidthPx: 1.2,
    nodeLabelFontSizePx: 14,
    nodeLabelLineHeightPx: 20,
    groupFill: "#f1f3f6",
    groupStroke: "#8a93a3",
    groupStrokeWidthPx: 1.4,
    groupLabelFontSizePx: 16,
    groupLabelLineHeightPx: 22,
    groupDepthOpacityStep: 0.12,
    edgeStroke: "#3f4652",
    edgeStrokeWidthPx: 1.4,
    edgeLabelFontSizePx: 12,
    edgeLabelLineHeightPx: 17,
    edgeLabelBackground: "#ffffff",
    arrowFill: "#3f4652",
    portFill: "#ffffff",
    portStroke: "#3f4652",
    portStrokeWidthPx: 1,
    portSizePx: 8,
    labelFontFamily: "Inter",
    minimumLabelFontSizePx: 10,
  }),
});

export const academicTheme: Theme = Object.freeze({
  id: "academic",
  version: "1.0.0",
  title: "Academic",
  colorScheme: "light",
  colors: Object.freeze({
    background: "#fdfcf9",
    foreground: "#1c1917",
    muted: "#78716c",
  }),
  typography: Object.freeze({
    proseFontFamily: "Inter",
    bodyFontWeight: 400,
    headingFontWeight: 700,
    lineHeight: 1.7,
    headingLineHeight: 1.3,
    paragraphSpacingEm: 1.1,
  }),
  geometry: Object.freeze({
    canvasWidthPx: 880,
    contentWidthPx: 700,
    paddingPx: 56,
  }),
  diagram: Object.freeze({
    nodeFill: "#ffffff",
    nodeStroke: "#44403c",
    nodeStrokeWidthPx: 1.2,
    nodeLabelFontSizePx: 15,
    nodeLabelLineHeightPx: 21,
    groupFill: "#f3f1ea",
    groupStroke: "#8a8377",
    groupStrokeWidthPx: 1.4,
    groupLabelFontSizePx: 17,
    groupLabelLineHeightPx: 24,
    groupDepthOpacityStep: 0.12,
    edgeStroke: "#44403c",
    edgeStrokeWidthPx: 1.4,
    edgeLabelFontSizePx: 12,
    edgeLabelLineHeightPx: 17,
    edgeLabelBackground: "#fdfcf9",
    arrowFill: "#44403c",
    portFill: "#fdfcf9",
    portStroke: "#44403c",
    portStrokeWidthPx: 1,
    portSizePx: 8,
    labelFontFamily: "Inter",
    minimumLabelFontSizePx: 10,
  }),
});

export const darkPresentationTheme: Theme = Object.freeze({
  id: "dark-presentation",
  version: "1.0.0",
  title: "Dark Presentation",
  colorScheme: "dark",
  colors: Object.freeze({
    background: "#0f172a",
    foreground: "#e2e8f0",
    muted: "#94a3b8",
  }),
  typography: Object.freeze({
    proseFontFamily: "Inter",
    bodyFontWeight: 400,
    headingFontWeight: 700,
    lineHeight: 1.5,
    headingLineHeight: 1.2,
    paragraphSpacingEm: 1,
  }),
  geometry: Object.freeze({
    canvasWidthPx: 1280,
    contentWidthPx: 1024,
    paddingPx: 64,
  }),
  diagram: Object.freeze({
    nodeFill: "#1e293b",
    nodeStroke: "#cbd5e1",
    nodeStrokeWidthPx: 1.2,
    nodeLabelFontSizePx: 16,
    nodeLabelLineHeightPx: 22,
    groupFill: "#16213a",
    groupStroke: "#94a3b8",
    groupStrokeWidthPx: 1.4,
    groupLabelFontSizePx: 18,
    groupLabelLineHeightPx: 25,
    groupDepthOpacityStep: 0.12,
    edgeStroke: "#cbd5e1",
    edgeStrokeWidthPx: 1.4,
    edgeLabelFontSizePx: 14,
    edgeLabelLineHeightPx: 20,
    edgeLabelBackground: "#0f172a",
    arrowFill: "#cbd5e1",
    portFill: "#0f172a",
    portStroke: "#cbd5e1",
    portStrokeWidthPx: 1,
    portSizePx: 8,
    labelFontFamily: "Inter",
    minimumLabelFontSizePx: 10,
  }),
});

export const builtInThemes: readonly Theme[] = Object.freeze([
  defaultTheme,
  academicTheme,
  darkPresentationTheme,
]);

export function copyAndFreezeTheme(theme: Theme): Theme {
  return Object.freeze({
    id: theme.id,
    version: theme.version,
    title: theme.title,
    colorScheme: theme.colorScheme,
    colors: Object.freeze({ ...theme.colors }),
    typography: Object.freeze({ ...theme.typography }),
    geometry: Object.freeze({ ...theme.geometry }),
    diagram: Object.freeze({ ...theme.diagram }),
  });
}
